# Generated by Django 3.2.5 on 2021-08-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restaurant',
            new_name='artist',
        ),
    ]
